name: Monthly Data Ingestion

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of every month
  workflow_dispatch:      # Allows manual trigger

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kaggle duckdb

      - name: Set up Kaggle API credentials
        env:
            KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}
        run: |
            mkdir -p ~/.kaggle
            if [ -z "$KAGGLE_JSON" ]; then
            echo "KAGGLE_JSON secret is missing or empty."
            exit 1
            fi
            echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
            chmod 600 ~/.kaggle/kaggle.json

      - name: Run data ingestion script
        run: python src/data_ingestion.py

      - name: Upload bronze data as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: bronze-data
          path: data/bronze/